import type { CaseLog } from "./supabase";

const now = Date.now();
const minsAgo = (m: number) => new Date(now - m * 60_000).toISOString();

export const SAMPLE_CASES: CaseLog[] = [
  {
    id: "s1",
    session_id: "sess_001",
    user_message: "I'm 32 weeks pregnant and bleeding heavily, also severe abdominal pain since this morning.",
    age_band: "30-39",
    contact_channel: "Web chat",
    reason_for_visit: "Heavy bleeding during pregnancy",
    urgency_level: "emergency",
    recommended_queue: "Labor & Delivery",
    escalation_required: true,
    red_flags: ["Heavy bleeding", "Severe abdominal pain", "Third trimester"],
    next_action: "Direct patient to ER immediately and notify on-call OB.",
    staff_summary: "32-week pregnant patient reporting heavy bleeding and severe abdominal pain. Possible placental abruption.",
    patient_message: "Please go to the nearest emergency room right away. We've alerted the on-call OB team.",
    human_readable_summary: "Third-trimester emergency with bleeding and pain — needs immediate ER care.",
    created_at: minsAgo(4),
  },
  {
    id: "s2",
    session_id: "sess_002",
    user_message: "Burning when I pee for 2 days, no fever. Can I get seen today?",
    age_band: "20-29",
    contact_channel: "SMS",
    reason_for_visit: "Suspected UTI",
    urgency_level: "urgent_same_day",
    recommended_queue: "Nurse triage",
    escalation_required: false,
    red_flags: [],
    next_action: "Offer same-day urgent slot, send urine sample instructions.",
    staff_summary: "Likely uncomplicated UTI, no systemic symptoms. Same-day appointment appropriate.",
    patient_message: "We can fit you in today. A nurse will call within the hour with next steps.",
    human_readable_summary: "Probable UTI, same-day visit recommended.",
    created_at: minsAgo(22),
  },
  {
    id: "s3",
    session_id: "sess_003",
    user_message: "Need to book my annual well-woman exam, prefer a Tuesday morning.",
    age_band: "40-49",
    contact_channel: "Web chat",
    reason_for_visit: "Annual well-woman exam",
    urgency_level: "routine",
    recommended_queue: "Scheduling",
    escalation_required: false,
    red_flags: [],
    next_action: "Route to scheduling team to offer Tuesday morning slots.",
    staff_summary: "Routine annual exam request. No symptoms reported.",
    patient_message: "Thanks — our scheduling team will reach out with Tuesday morning options.",
    human_readable_summary: "Routine annual exam booking request.",
    case_status: "reviewed",
    created_at: minsAgo(58),
  },
  {
    id: "s4",
    session_id: "sess_004",
    user_message: "Can you send my lab results from last week to my new PCP?",
    age_band: "50-59",
    contact_channel: "Patient portal",
    reason_for_visit: "Records request",
    urgency_level: "admin_only",
    recommended_queue: "Front desk",
    escalation_required: false,
    red_flags: [],
    next_action: "Forward to medical records for release of information processing.",
    staff_summary: "Records release request. No clinical action required.",
    patient_message: "We'll forward your request to medical records — they'll be in touch within 2 business days.",
    human_readable_summary: "Administrative records transfer request.",
    case_status: "closed",
    created_at: minsAgo(94),
  },
  {
    id: "s5",
    session_id: "sess_005",
    user_message: "Missed period for 6 weeks, took a home test and it was positive. What should I do next?",
    age_band: "20-29",
    contact_channel: "Web chat",
    reason_for_visit: "Confirming pregnancy",
    urgency_level: "routine",
    recommended_queue: "OB scheduling",
    escalation_required: false,
    red_flags: [],
    next_action: "Schedule first prenatal visit within 2-3 weeks.",
    staff_summary: "New pregnancy confirmation request. Standard prenatal intake.",
    patient_message: "Congratulations — we'd like to schedule your first prenatal visit. Someone will reach out today.",
    human_readable_summary: "Newly confirmed pregnancy, routine prenatal intake.",
    created_at: minsAgo(140),
  },
];
